name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_TOKEN }}     # (PAT)

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .              
          push: true               
          tags: dyoung1023/young-ceg3120:latest

      - name: Display Image Name
        run: echo "Pushed Docker image: dyoung1023/young-ceg3120:latest"

